"""add_due_date_and_assignee_to_cards

Revision ID: 245a24abea14
Revises: 0ccb38650d84
Create Date: 2026-02-23 18:33:30.466550

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "245a24abea14"
down_revision: Union[str, Sequence[str], None] = "0ccb38650d84"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cards", sa.Column("due_date", sa.DateTime(), nullable=True))
    op.add_column("cards", sa.Column("assignee", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cards", "assignee")
    op.drop_column("cards", "due_date")
    # ### end Alembic commands ###
